id: 195c27d6717e4a1faaf2c6200afcc8b2
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_336-The_Rite_for_the_Protocols_Associated_with_Carrying_the_Ringing_Staff-v2
  language: bo
  author: ''
  volume: {}
